# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-05-01 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletable',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
