# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-05-02 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunbo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunbo',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
