# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-05-02 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunbo', '0002_auto_20190502_1550'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lunbo',
            table=None,
        ),
    ]
