# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-05-02 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunbo', '0003_auto_20190502_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunbo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
